version: '3.8'

services:

  # --- PostgreSQL (simule la base Odoo) ---
  postgres:
    image: postgres:15
    container_name: odoo_postgres
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo123
      POSTGRES_DB: odoo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- ClickHouse (Data Warehouse) ---
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_dwh
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  # --- Apache Airflow ---
  airflow:
    image: apache/airflow:2.9.0
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://odoo:odoo123@postgres/odoo_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: webserver

  # --- Metabase (Visualisation) ---
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data

volumes:
  postgres_data:
  clickhouse_data:
  metabase_data: